services:
  - type: web
    name: cineverse-frontend
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_APP_NAME
        value: Cineverse
      - key: VITE_TMDB_BASE_URL
        value: https://api.themoviedb.org/3
      - key: VITE_TMDB_API_KEY
        fromSecret: VITE_TMDB_API_KEY
      - key: VITE_API_BASE_URL
        fromSecret: VITE_API_BASE_URL
      - key: VITE_APP_ENVIRONMENT
        value: production
      - key: VITE_APP_VERSION
        value: latest
      - key: VITE_ENABLE_ANALYTICS
        value: "true"
      - key: VITE_ENABLE_LOGGING
        value: "false"
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains
      - path: /static/(.*)
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    buildFilter:
      paths:
        - src/**
        - public/**
        - package.json
        - package-lock.json
        - tsconfig.json
        - vite.config.ts
        - tailwind.config.js
        - postcss.config.js
        - render.yaml
      ignoredPaths:
        - README.md
        - .github/**
        - DEPLOYMENT.md
        - DOCKER.md
        - WARP.md
        - *.md
        - test-*
        - docker/**
